### ISSUE TITLE
Can I somehow reuse sql pack connections in Stackstorm actions?

### ISSUE THREAD

**Issue by gnudiff** [StackStorm-Exchange/stackstorm-sql#17]
I would like to keep my connection info centralized (if not having an existing reusable pool of actual connections).

Can I, and if yes, -- how -- access the sql pack connection info from other stackstorm python actions?

**Comment by bishopbm1** [comment]
Yes and No,

The sql pack config cannot be used in other packs unfortunately. But you can make the data easily reusable by using the KV store . You sql config would look like the below then you can either use the info directly from the KV store or create another config for your custom pack.

```
---
connections:
  postgresql:
    host: "{{ st2kv.system.postgresql.host }}"
    username: "{{ st2kv.system.postgresql.username }}"
    password: "{{ st2kv.system.postgresql.password }}"
    database: "{{ st2kv.system.postgresql.database }}"
    port: "{{ st2kv.system.postgresql.port }}"
    drivername: "{{ st2kv.system.postgresql.drivername }}"
```
