### ISSUE TITLE
Passing query result to next action?

### ISSUE THREAD

**Issue by gnudiff** [StackStorm-Exchange/stackstorm-sql#18]
I am trying to integrate sql query in my Orquestra workflow:

```
--
version: 1.0
name: Daily report
description: Get daily stats 
tasks:
  task1:
    action: sql.query
    input:
      connection: my_conn
      query: "SELECT ... 
                    <long running query>
                  "
    next:
      publish: data="<% result() %>"
      do: task2
  task2:
    action: "reports.act1"
    input:
      data: "<% ctx(data) %>"

```
And I get error: 
```
  errors:
  - message: The spec is not type of list.
```

What gives?

act1 is just a simple python action which accepts data parameter and prints out its type and contents.

**Comment by bishopbm1** [comment]
Can you share what your action file looks like also can you share what the execution tree looks like? Also as a test if you take away task2 does it run successfully?

**Comment by ShawnHardwick** [comment]
The `next` key is expecting a `list`, not a `dict`.
https://docs.stackstorm.com/orquesta/languages/orquesta.html#task-transition-model

```
--
version: 1.0
name: Daily report
description: Get daily stats 
tasks:
  task1:
    action: sql.query
    input:
      connection: my_conn
      query: "SELECT ... 
                    <long running query>
                  "
    next:
      - publish: data="<% result() %>"
        do: task2
  task2:
    action: "reports.act1"
    input:
      data: "<% ctx(data) %>"
```
